# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    container: node:10.18-jessie
    
    # Service containers to run with `container-job`
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out Git Repository
      uses: actions/checkout@v2
      
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install packages
      run: |
        npm ci

    - name: Setup test database & test
      env:
        SEQUELIZE_DATABASE: postgres
        SEQUELIZE_USERNAME: postgres
        SEQUELIZE_PASSWORD: postgres
        SEQUELIZE_HOST: postgres
      run: |
        npm run migrate
        npm run seed
        npm test

  build:
  
    # The job it requires to finish first
    needs: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Check out Git Repository
      uses: actions/checkout@v2
    
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker build
      run: |
        docker build -t thekhaledrizk/intouch-store-backend .
        
    - name: Docker push
      run: |
        docker push thekhaledrizk/intouch-store-backend
